name: Build and Push Docker Image

on: 
  push:
    branches:
      - main

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest
