name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install Flask==3.0.3 Flask-Cors==4.0.1 h5py==3.11.0 joblib==1.4.2 keras==3.5.0 numpy==1.26.4 pillow==10.4.0 reportlab==4.2.2 scikit-learn==1.5.0 tensorflow==2.17.0 Flask-SQLAlchemy==3.1.1 werkzeug==3.0.4 Flask-Login==0.6.3 matplotlib~=3.10.0 plotly~=5.24.1 SQLAlchemy~=2.0.36
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
